globalVars = {
    stepSize = 5,
    dontReplaceSV = false,
    upscroll = false,
    colorThemeIndex = 9,
    styleThemeIndex = 1,
    effectFPS = 90,
    cursorTrailIndex = 1,
    cursorTrailShapeIndex = 1,
    cursorTrailPoints = 10,
    cursorTrailSize = 5,
    snakeSpringConstant = 1,
    cursorTrailGhost = false,
    rgbPeriod = 2,
    drawCapybara = false,
    drawCapybara2 = false,
    drawCapybara312 = false,
    selectTypeIndex = 1,
    placeTypeIndex = 1,
    editToolIndex = 1,
    showPresetMenu = false,
    scrollGroupIndex = 1,
    hideSVInfo = false,
    showVibratoWidget = false,
    showNoteDataWidget = false,
    showMeasureDataWidget = false,
    ignoreNotesOutsideTg = false,
    advancedMode = false,
    hideAutomatic = false,
    pulseCoefficient = 0,
    pulseColor = {},
    useCustomPulseColor = false,
    hotkeyList = {},
    customStyle = {},
    dontPrintCreation = false,
    equalizeLinear = false,
    defaultProperties = { settings = {}, menu = {} },
    presets = {}
}

DEFAULT_GLOBAL_VARS = table.duplicate(globalVars)

function setGlobalVars(tempGlobalVars)
    globalVars.useCustomPulseColor = truthy(tempGlobalVars.useCustomPulseColor)
    globalVars.pulseColor = table.vectorize4(tempGlobalVars.pulseColor)
    globalVars.pulseCoefficient = math.toNumber(tempGlobalVars.pulseCoefficient)
    globalVars.stepSize = math.toNumber(tempGlobalVars.stepSize)
    globalVars.dontReplaceSV = truthy(tempGlobalVars.dontReplaceSV)
    globalVars.upscroll = truthy(tempGlobalVars.upscroll)
    globalVars.colorThemeIndex = math.toNumber(tempGlobalVars.colorThemeIndex)
    globalVars.styleThemeIndex = math.toNumber(tempGlobalVars.styleThemeIndex)
    globalVars.rgbPeriod = math.toNumber(tempGlobalVars.rgbPeriod)
    globalVars.cursorTrailIndex = math.toNumber(tempGlobalVars.cursorTrailIndex)
    globalVars.cursorTrailShapeIndex = math.toNumber(tempGlobalVars.cursorTrailShapeIndex)
    globalVars.effectFPS = math.toNumber(tempGlobalVars.effectFPS)
    globalVars.cursorTrailPoints = math.toNumber(tempGlobalVars.cursorTrailPoints)
    globalVars.cursorTrailSize = math.toNumber(tempGlobalVars.cursorTrailSize)
    globalVars.snakeSpringConstant = math.toNumber(tempGlobalVars.snakeSpringConstant)
    globalVars.cursorTrailGhost = truthy(tempGlobalVars.cursorTrailGhost)
    globalVars.drawCapybara = truthy(tempGlobalVars.drawCapybara)
    globalVars.drawCapybara2 = truthy(tempGlobalVars.drawCapybara2)
    globalVars.drawCapybara312 = truthy(tempGlobalVars.drawCapybara312)
    globalVars.ignoreNotes = truthy(tempGlobalVars.ignoreNotesOutsideTg)
    globalVars.hideSVInfo = truthy(tempGlobalVars.hideSVInfo)
    globalVars.showVibratoWidget = truthy(tempGlobalVars.showVibratoWidget)
    globalVars.showNoteDataWidget = truthy(tempGlobalVars.showNoteDataWidget)
    globalVars.showMeasureDataWidget = truthy(tempGlobalVars.showMeasureDataWidget)
    globalVars.advancedMode = truthy(tempGlobalVars.advancedMode)
    globalVars.hideAutomatic = truthy(tempGlobalVars.hideAutomatic)
    globalVars.dontPrintCreation = truthy(tempGlobalVars.dontPrintCreation)
    globalVars.hotkeyList = table.validate(DEFAULT_HOTKEY_LIST, table.duplicate(tempGlobalVars.hotkeyList), true)
    globalVars.customStyle = tempGlobalVars.customStyle or table.construct()
    globalVars.equalizeLinear = truthy(tempGlobalVars.equalizeLinear)
end
